default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: rejected_plates_development

test: &TEST
  <<: *default
  database: rejected_plates_test

production:
  <<: *default
  database: rejected_plates_production
  username: 
  password: 